### ISSUE TITLE
why do you sample using a random function?

### ISSUE THREAD

**Issue by lingxiangwu** [DevinZ1993/Chinese-Poetry-Generator#2]
Hi Nan,
I have a question pretty confused. On generate.py line 204, why do you use random.random() < prob_list[j]/prob_sums[j] to get the character?  I've tried the argmax method, but it always generate frequently appeared character like "不" “一”.

**Comment by DevinZ1993** [comment]
On my laptop, after proper training, it doesn't only print out most frequent characters if I use argmax instead of random method. I'm not sure what is wrong in your case.

Here are some outputs when I used argmax to select characters:

[u'走', u'眼', u'书', u'流水']
u'千里通忠非滞国'
u'不是卢郎麈颊窠'
u'不是一樽成此意'
u'不知流水过长柯'

[u'山', u'灯', u'锦', u'人']
u'山泽山前万里林'
u'月看山下有清秋'
u'不知人意皆开柳'
u'不是人间掘子求'

[u'动', u'通', u'须', u'风']
u'绿叶凝氲冻雪鸦'
u'碧云千叠护空滩'
u'不知景罢非何处'
u'不信春愁不有坛'

[u'早', u'遥', u'偏来', u'萧萧']
u'晚上危陵忆故乡'
u'谁知一句数千峰'
u'当时不解回生驾'
u'一夜风光一度风'

[u'一年', u'旧', u'白头', u'雪']
u'百年赊处在山翁'
u'不到长榛问故人'
u'不是相逢皆有否'
u'讵分红粉露垂仁'

[u'风流', u'诗句', u'今日', u'兼']
u'风流无处好'
u'不肯看春来'
u'今朝又何处'
u'不知胜社徕'

[u'曾', u'双眉', u'古今', u'人间']
u'七佛忍闻湘海游'
u'不知春草自生涯'
u'不知人事无多事'
u'不是人间有世鸦'

As to random character selection, it is only used to make the generator seem more "creative" than a silly program. After all, who wants a poem generator always print out the same poem given the same input context?

**Comment by lingxiangwu** [comment]
Thanks for your comments. It makes sense now. 
By the way, using argmax, it generated poem for me, but the "不" may appear more than three times in a poem. More training can solve this problem. 
Thanks.

**Comment by DevinZ1993** [comment]
Yep, it took me a long time to train this model on a 4GB-memory laptop without GPU acceleration. Probably over ten hours or so.
